import camelCase from 'lodash/camelCase';
import clearDay from './Icons/clear-day.png';
import clearNight from './Icons/clear-night.png';
import cloudy from './Icons/cloudy.png';
import fog from './Icons/fog.png';
import hail from './Icons/hail.png';
import partlyCloudyDay from './Icons/partly-cloudy-day.png';
import partlyCloudyNight from './Icons/partly-cloudy-night.png';
import rainSnowShowersDay from './Icons/rain-snow-showers-day.png';
import rainSnowShowersNight from './Icons/rain-snow-showers-night.png';
import rainSnow from './Icons/rain-snow.png';
import rain from './Icons/rain.png';
import showersDay from './Icons/showers-day.png';
import showersNight from './Icons/showers-night.png';
import sleet from './Icons/sleet.png';
import snowShowersDay from './Icons/snow-showers-day.png';
import snowShowersNight from './Icons/snow-showers-night.png';
import snow from './Icons/snow.png';
import thunderRain from './Icons/thunder-rain.png';
import thunderShowersDay from './Icons/thunder-showers-day.png';
import thunderShowersNight from './Icons/thunder-showers-night.png';
import thunder from './Icons/thunder.png';
import wind from './Icons/wind.png';

export default function getIcon(icon) {
  const getIcon = camelCase(icon);
  if (getIcon === 'clearDay') return clearDay;
  if (getIcon === 'clearNight') return clearNight;
  if (getIcon === 'cloudy') return cloudy;
  if (getIcon === 'fog') return fog;
  if (getIcon === 'hail') return hail;
  if (getIcon === 'partlyCloudyDay') return partlyCloudyDay;
  if (getIcon === 'partlyCloudyNight') return partlyCloudyNight;
  if (getIcon === 'rainSnowShowersDay') return rainSnowShowersDay;
  if (getIcon === 'rainSnowShowersNight') return rainSnowShowersNight;
  if (getIcon === 'rainSnow') return rainSnow;
  if (getIcon === 'rain') return rain;
  if (getIcon === 'showersDay') return showersDay;
  if (getIcon === 'showersNight') return showersNight;
  if (getIcon === 'sleet') return sleet;
  if (getIcon === 'snowShowersDay') return snowShowersDay;
  if (getIcon === 'snowShowersNight') return snowShowersNight;
  if (getIcon === 'snow') return snow;
  if (getIcon === 'thunderRain') return thunderRain;
  if (getIcon === 'thunderShowersDay') return thunderShowersDay;
  if (getIcon === 'thunderShowersNight') return thunderShowersNight;
  if (getIcon === 'thunder') return thunder;
  if (getIcon === 'wind') return wind;
}
